### ISSUE TITLE
npm run prod fails

### ISSUE THREAD

**Issue by BitLox** [cssninjaStudio/krypton#20]
Hi, nice template.

`nm run dev` works fine, but when I want to shift to production  serving the site I get an error:
```
player1@MacBook krypton % npm run prod

> krypton@4.0.0 prod /Users/player1/Documents/krypton
> gulp prod

[22:33:11] Using gulpfile ~/Documents/krypton/gulpfile.js
[22:33:11] Task never defined: prod
[22:33:11] To list available tasks, try running: gulp --tasks
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! krypton@4.0.0 prod: `gulp prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the krypton@4.0.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
The full log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/player1/.nvm/versions/node/v12.18.0/bin/node',
1 verbose cli   '/Users/player1/.nvm/versions/node/v12.18.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prod'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.18.0
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle krypton@4.0.0~preprod: krypton@4.0.0
6 info lifecycle krypton@4.0.0~prod: krypton@4.0.0
7 verbose lifecycle krypton@4.0.0~prod: unsafe-perm in lifecycle true
8 verbose lifecycle krypton@4.0.0~prod: PATH: /Users/player1/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/player1/Documents/krypton/node_modules/.bin:/usr/local/share/android-sdk/build-tools/28.0.3:/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk/tools:/usr/local/opt/gradle/bin:/usr/local/opt/maven/bin:/usr/local/opt/ant/bin:/usr/local/sbin:/Users/player1/.nvm/versions/node/v12.18.0/bin:/Users/player1/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle krypton@4.0.0~prod: CWD: /Users/player1/Documents/krypton
10 silly lifecycle krypton@4.0.0~prod: Args: [ '-c', 'gulp prod' ]
11 silly lifecycle krypton@4.0.0~prod: Returned: code: 1  signal: null
12 info lifecycle krypton@4.0.0~prod: Failed to exec prod script
13 verbose stack Error: krypton@4.0.0 prod: `gulp prod`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/player1/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/player1/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid krypton@4.0.0
15 verbose cwd /Users/player1/Documents/krypton
16 verbose Darwin 20.3.0
17 verbose argv "/Users/player1/.nvm/versions/node/v12.18.0/bin/node" "/Users/player1/.nvm/versions/node/v12.18.0/bin/npm" "run" "prod"
18 verbose node v12.18.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error krypton@4.0.0 prod: `gulp prod`
22 error Exit status 1
23 error Failed at the krypton@4.0.0 prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Suggestions?

**Comment by swdreams** [comment]
Same issue. When can it be fixed?

**Comment by mmulika** [comment]
same issue
